version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c6:6f:03:bf:5a:bb:ce:24:8d:64:cd:30:3a:73:f8:75"
      - run:
          name: Deploy
          command: |
            # 6- Give the ingress rule some time to propogate
            sleep 5
            # 7- SSH to the server to deploy
            # TODO Change to your username
            EC2_USERNAME=ubuntu
            # TODO Change to your server's URL or public IP
            EC2_PUBLIC_DNS=ec2-3-82-229-178.compute-1.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS 'sudo apt update && sudo apt install apache2 -y'
            # TODO Perform steps to deploy
            # .
            # .
