version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c6:6f:03:bf:5a:bb:ce:24:8d:64:cd:30:3a:73:f8:75"
      - run:
          name: Deploy
          command: |
            sleep 5

            EC2_USERNAME=ubuntu

            EC2_PUBLIC_DNS=ec2-3-94-179-178.compute-1.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS 'sudo apt update && sudo apt install apache2 -y'
